'use strict';
// Front-end concept only. All changes live in this page's memory; no network or storage writes.
(() => {
  const initial = [
    {id:'touring',name:'Volvo XC60',plate:'ABC-123',year:2020,km:184320,events:[
      {id:'oil',type:'Moottoriöljyn vaihto',date:'2026-09-23',km:184320,cost:'129',note:'Öljy ja öljynsuodatin vaihdettu. Kuvitteellinen esimerkkimerkintä.'},
      {id:'filter',type:'Ilmansuodattimen vaihto',date:'2026-05-12',km:182450,cost:'35',note:'Moottorin ilmansuodatin vaihdettu.'},
      {id:'tyres',type:'Renkaiden vaihto',date:'2026-04-05',km:181900,cost:'50',note:'Kesärenkaat vaihdettu alle.'},
      {id:'inspection',type:'Katsastus',date:'2026-02-15',km:181120,cost:'75',note:'Määräaikaiskatsastus hyväksytty. Ei korjauskehotuksia. Kuvitteellinen merkintä.'},
      {id:'brakes',type:'Jarruhuolto',date:'2025-11-14',km:174860,cost:'485',note:'Etujarrulevyt ja -palat vaihdettu. Jarrujen toiminta tarkistettu koeajolla. Kuvitteellinen työ ja hinta.'},
      {id:'annual',type:'Vuosihuolto',date:'2025-09-18',km:169540,cost:'329',note:'Öljyn ja öljynsuodattimen vaihto, raitisilmasuodattimen vaihto sekä nesteiden ja valojen tarkistus. Kuvitteellinen huoltokäynti, ei valmistajan huolto-ohjelma.'},
      {id:'winter',type:'Renkaiden vaihto',date:'2024-10-28',km:151200,cost:'65',note:'Talvirenkaat asennettu. Rengaspaineet tarkistettu. Kuvitteellinen merkintä.'},
      {id:'service2024',type:'Vuosihuolto',date:'2024-09-12',km:148300,cost:'310',note:'Öljy ja öljynsuodatin vaihdettu. Alustan ja jarrujen silmämääräinen tarkistus. Kuvitteellinen huolto ja kustannus.'}
    ]},
    {id:'city',name:'Kaupunkiauto',plate:'XYZ-789',year:2018,km:92450,events:[
      {id:'service',type:'Huolto',date:'2026-08-17',km:92450,cost:'220',note:'Vuosihuolto. Kuvitteellinen esimerkkimerkintä.'},
      {id:'tyres2',type:'Renkaiden vaihto',date:'2026-04-07',km:89100,cost:'45',note:'Kesärenkaat vaihdettu alle.'}
    ]}
  ];
  const kinds=['Huolto','Vuosihuolto','Jarruhuolto','Moottoriöljyn vaihto','Ilmansuodattimen vaihto','Renkaiden vaihto','Katsastus','Muu tapahtuma'];
  const guidance={
    welcome:['01 / 04','Tervetuloa kyytiin.','Aloita demo puhelimen sinisestä painikkeesta. Et tarvitse tiliä tai latausta.'],
    vehicles:['02 / 04','Kaksi autoa. Oma historia.','Avaa jompikumpi esimerkkiautoista. Molemmilla on oma mittarilukema ja erillinen tapahtumahistoria.'],
    vehicle:['03 / 04','Jokainen merkintä kertoo.','Avaa tapahtuma nähdäksesi sen tiedot. Tai paina Lisää tapahtuma ja kokeile päiväkirjaa itse.'],
    add:['04 / 04','Kokeile uutta merkintää.','Valitse tapahtuma, päivämäärä ja ajokilometrit. Tallennuksen jälkeen merkintä löytyy auton historiasta.'],
    event:['03 / 04','Yksityiskohdat tallessa.','Päivämäärä, mittarilukema ja muistiinpanot yhdessä näkymässä. Palaa historiaan vasemman yläkulman nuolesta.']
  };
  let cars=structuredClone(initial),sequence=0,notice='';
  const screen=document.getElementById('app-screen');
  const escape=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const number=value=>Number(value).toLocaleString('fi-FI');
  const date=value=>new Intl.DateTimeFormat('fi-FI').format(new Date(value+'T12:00:00'));
  const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
  const carImage='<img src="car.svg" width="600" height="260" alt="Auton kuvitus">';
  const vehicleImage=c=>c.id==='touring'?'<img class="vehicle-photo" src="volvo-xc60.jpg" width="960" height="640" alt="Volvo XC60, toisen sukupolven mallikuva">':carImage;
  const top=()=>'<div class="app-top"><span class="app-brand">AJOURA</span><span class="demo-label">KONSEPTIDEMO</span></div>';
  const back=(target,label)=>`<a class="app-back" href="#${target}">← ${label}</a>`;
  const route=()=>{const [view='welcome',id='',eventId='']=(location.hash.slice(1)||'welcome').split('/');return {view,id,eventId};};
  const go=target=>{if(location.hash==='#'+target)render();else location.hash=target;};
  const eventIcon=type=>type==='Katsastus'?'✓':type==='Renkaiden vaihto'?'◉':'↻';
  function welcome(){return `${top()}<div class="welcome"><img class="welcome-logo" src="mark.svg" alt="" width="49" height="49"><h2>Hyvä matka<br><span>jää muistiin.</span></h2><p>Autosi tapahtumat, mittarilukemat ja huollot. Yhdessä omassa päiväkirjassa.</p><div class="welcome-art">${carImage}<p>Yksi selkeä näkymä autosi matkaan.</p></div><a class="app-button" href="#vehicles">Aloita kokeilu <span aria-hidden="true">→</span></a><p class="app-fineprint">Kuvitteelliset tiedot. Ei kirjautumista.<br>Merkinnät nollautuvat sivun päivityksessä.</p></div>`;}
  function vehicles(){return `${top()}<p class="app-greeting">Tervetuloa omaan talliin.</p><h2 class="app-heading">Omat ajoneuvot</h2><p class="app-subtitle">Valitse auto ja jatka sen tarinaa.</p>${cars.map(c=>`<a class="vehicle-card" href="#vehicle/${c.id}" aria-label="Avaa ${c.name}"><span class="mini-label">${escape(c.plate)} · ${c.year}</span>${vehicleImage(c)}<div class="vehicle-line"><div><h3>${c.name}</h3><p>Oma ajoneuvopäiväkirja</p></div><span class="round-arrow" aria-hidden="true">↗</span></div><div class="vehicle-mileage"><span>${number(c.km)} km</span><span>${c.events.length} tapahtumaa</span></div></a>`).join('')}<p class="app-fineprint">Demossa on kaksi valmista esimerkkiautoa.</p><button class="app-back" data-reset type="button">↻ Palauta demon lähtötiedot</button>`;}
  function vehicle(c){const sorted=[...c.events].sort((a,b)=>b.date.localeCompare(a.date)||b.km-a.km);return `${back('vehicles','Ajoneuvot')}<div class="vehicle-hero">${vehicleImage(c)}<h2 class="app-heading">${c.name}</h2><p>${escape(c.plate)} · ${c.year}</p></div>${notice?`<p class="success-note" role="status">${escape(notice)}</p>`:''}<div class="app-stats"><div><strong>${number(c.km)} <small>km</small></strong><span>Mittarilukema</span></div><div><strong>${c.events.length}</strong><span>Tapahtumaa</span></div></div><a class="app-button" href="#add/${c.id}">＋ Lisää tapahtuma</a><div class="history-heading"><h3>Tapahtumahistoria</h3><span>Uusin ensin</span></div><ul class="event-list">${sorted.map(e=>`<li><a class="event-row" href="#event/${c.id}/${e.id}"><span class="event-symbol" aria-hidden="true">${eventIcon(e.type)}</span><span><strong>${escape(e.type)}</strong><small>${date(e.date)} · ${number(e.km)} km</small></span><span class="chevron" aria-hidden="true">›</span></a></li>`).join('')}</ul><p class="app-note">Kuvitteellinen historia, rekisteritunnus ja hinnat. Ei kuvan auton tietoja. ${c.id==='touring'?'<a href="credits.html" target="_blank" rel="noopener">Mallikuvan lähde ↗</a>':''}</p>`;}
  function add(c){return `${back('vehicle/'+c.id,'Ajoneuvo')}<h2 class="app-heading">Uusi tapahtuma</h2><p class="app-subtitle">${c.name} · ${c.plate}<br>Pieni merkintä. Yksi asia vähemmän muistettavana.</p><form class="app-form" id="event-form"><label>Tapahtuma<select name="type" required><option value="">Valitse tapahtuman tyyppi</option>${kinds.map(k=>`<option>${k}</option>`).join('')}</select></label><label>Päivämäärä<input name="date" type="date" value="${today()}" max="${today()}" min="${c.year}-01-01" required></label><label>Mittarilukema (km)<input name="km" type="number" min="0" max="2000000" step="1" inputmode="numeric" placeholder="${c.km}" required></label><p class="field-help">Viimeisin kirjattu lukema: ${number(c.km)} km. Voit lisätä myös vanhemman tapahtuman.</p><label>Kustannus (€) <small>· valinnainen</small><input name="cost" type="number" min="0" max="1000000" step="0.01" inputmode="decimal" placeholder="0,00"></label><label>Muistiinpano <small>· valinnainen</small><textarea name="note" maxlength="300" rows="3" placeholder="Esim. öljy ja suodatin vaihdettu"></textarea></label><p class="error-note" id="form-error" role="alert"></p><div class="form-actions"><button class="app-button" type="submit">Tallenna demoon</button><a class="app-button secondary" href="#vehicle/${c.id}">Peruuta</a></div><p class="app-fineprint">Merkintä säilyy vain tämän sivun muistissa.<br>Älä kirjoita oikeita henkilötietoja.</p></form>`;}
  function detail(c,e){return `${back('vehicle/'+c.id,'Tapahtumahistoria')}<div class="detail-icon" aria-hidden="true">${eventIcon(e.type)}</div><h2 class="app-heading">${escape(e.type)}</h2><p class="app-subtitle">${c.name} · ${c.plate}</p><dl class="detail-list"><div><dt>PÄIVÄMÄÄRÄ</dt><dd>${date(e.date)}</dd></div><div><dt>MITTARILUKEMA</dt><dd>${number(e.km)} km</dd></div><div><dt>KUSTANNUS</dt><dd>${e.cost!==''?number(e.cost)+' €':'Ei merkitty'}</dd></div><div><dt>MUISTIINPANO</dt><dd>${e.note?escape(e.note):'Ei muistiinpanoa.'}</dd></div></dl><a class="app-button secondary" href="#vehicle/${c.id}">Takaisin ajoneuvoon</a><p class="app-fineprint">${e.id.startsWith('new')?'Tässä demossa lisätty kokeilumerkintä.':'Kuvitteellinen esimerkkimerkintä.'}</p>`;}
  function render(){let {view,id,eventId}=route();let c=cars.find(c=>c.id===id);if(!guidance[view]||(['vehicle','add','event'].includes(view)&&!c)){history.replaceState(null,'','#vehicles');view='vehicles';}let e=c?.events.find(e=>e.id===eventId);if(view==='event'&&!e){history.replaceState(null,'','#vehicle/'+c.id);view='vehicle';}let html=view==='welcome'?welcome():view==='vehicles'?vehicles():view==='vehicle'?vehicle(c):view==='add'?add(c):detail(c,e);screen.innerHTML='<div class="screen-content">'+html+'</div>';screen.scrollTop=0;screen.focus({preventScroll:true});const g=guidance[view];document.getElementById('guide-number').textContent=g[0];document.getElementById('guide-title').textContent=g[1];document.getElementById('guide-copy').textContent=g[2];document.querySelectorAll('[data-step]').forEach(el=>el.classList.toggle('active',el.dataset.step===(view==='event'?'vehicle':view)));document.title='AJOURA App — '+({welcome:'Tervetuloa',vehicles:'Omat ajoneuvot',vehicle:c?.name,add:'Uusi tapahtuma',event:e?.type}[view]);notice='';}
  screen.addEventListener('submit',event=>{if(event.target.id!=='event-form')return;event.preventDefault();const form=event.target;if(!form.reportValidity())return;const c=cars.find(c=>c.id===route().id);if(!c)return;const data=new FormData(form);const km=Number(data.get('km'));const when=String(data.get('date'));const type=String(data.get('type'));const cost=String(data.get('cost'));if(!kinds.includes(type)||!Number.isSafeInteger(km)||km<0||km>2000000||!/^\d{4}-\d{2}-\d{2}$/.test(when)||when>today()||when<c.year+'-01-01'||(cost!==''&&(!Number.isFinite(Number(cost))||Number(cost)<0))){document.getElementById('form-error').textContent='Tarkista päivämäärä ja mittarilukema.';return;}c.events.push({id:'new'+(++sequence),type,date:when,km,cost,note:String(data.get('note')).trim().slice(0,300)});c.km=Math.max(c.km,km);notice='✓ Tapahtuma lisätty demoon.';document.getElementById('demo-announcement').textContent=type+' lisätty ajoneuvolle '+c.name;go('vehicle/'+c.id);});
  function reset(){cars=structuredClone(initial);sequence=0;notice='';document.getElementById('demo-announcement').textContent='Demo palautettu lähtötilanteeseen.';go('welcome');}
  document.getElementById('reset-demo').addEventListener('click',reset);
  screen.addEventListener('click',event=>{if(event.target.closest('[data-reset]'))reset();});
  document.querySelector('.skip-link').addEventListener('click',event=>{event.preventDefault();screen.focus();});
  window.addEventListener('hashchange',render);
  render();
})();
